# Configuration file of Oort training experiment
exp_path: $HOME/fl/iFedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run oort (in order)
setup_commands:
    - source /sw/csi/anaconda3/4.4.0/binary/anaconda3/etc/profile.d/conda.sh
    - conda activate $HOME/fl/iFedScale/env
    - export NCCL_SOCKET_IFNAME='ib0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/fl/iFedScale/core/evals # Path of log files
    - job_name: cifar10                   # Generate logs under this folder: log_path/job_name/time_stamp
    - task: cv
    - total_worker: 10                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: cifar10                     # Dataset: openImg, google_speech, stackoverflow
    #- data_dir: $DATA_PATH                            # Path of the dataset
    #- data_map_file: $DATA_PATH/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    - data_dir: $HOME/fl/data/          #/run/user/172503/data/
    - device_conf_file: $HOME/fl/iFedScale/dataset/data/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: $HOME/fl/iFedScale/dataset/data/device_info/client_behave_trace
    - model: resnet18                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - sample_mode: oort
    - gradient_policy: yogi                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 10                     # How many rounds to run a testing on the testing set
    - epochs: 1000                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 41                       # Remove clients w/ less than 21 samples
    - num_loaders: 1
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 2
    - learning_rate: 0.01
    - batch_size: 40
    - test_bsz: 40
    - use_wandb: 1
    - stale_update: 0
    - deadline: 0                      # -1 use the moving average and last worker duration, -2 use the moving average and target_ratio worker duration
    - target_ratio: 0.8
    - random_behv: 1
    - last_worker: 0
    - avail_priority: 1
    - partitioning: 1
    - zipf_param: 1.95
    - filter_class_ratio: 0.4
    - total_clients: 1000
